//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeSen.Helpers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeSen.Helpers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;cities xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;city&gt;
        ///		&lt;id&gt;+1201&lt;/id&gt;
        ///		&lt;countryID&gt;1&lt;/countryID&gt;
        ///		&lt;name&gt;New Jersey&lt;/name&gt;
        ///	&lt;/city&gt;
        ///	&lt;city&gt;
        ///		&lt;id&gt;+1202&lt;/id&gt;
        ///		&lt;countryID&gt;1&lt;/countryID&gt;
        ///		&lt;name&gt;Washington DC&lt;/name&gt;
        ///	&lt;/city&gt;
        ///	&lt;city&gt;
        ///		&lt;id&gt;+1203&lt;/id&gt;
        ///		&lt;countryID&gt;1&lt;/countryID&gt;
        ///		&lt;name&gt;Connecticut&lt;/name&gt;
        ///	&lt;/city&gt;
        ///	&lt;city&gt;
        ///		&lt;id&gt;+1204&lt;/id&gt;
        ///		&lt;countryID&gt;107&lt;/countryID&gt;
        ///		&lt;name&gt;Manitoba&lt;/name&gt;
        ///	&lt;/city&gt;
        ///	&lt;city&gt;
        ///		&lt;id&gt;+120 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;countries xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;country&gt;
        ///		&lt;id&gt;1&lt;/id&gt;
        ///		&lt;countryCode&gt;1&lt;/countryCode&gt;
        ///		&lt;name&gt;United States&lt;/name&gt;
        ///		&lt;sameAreaRule&gt;G&lt;/sameAreaRule&gt;
        ///		&lt;longDistanceRule&gt;N1FG&lt;/longDistanceRule&gt;
        ///		&lt;internationalRule&gt;S011EFG&lt;/internationalRule&gt;
        ///	&lt;/country&gt;
        ///	&lt;country&gt;
        ///		&lt;id&gt;101&lt;/id&gt;
        ///		&lt;countryCode&gt;1&lt;/countryCode&gt;
        ///		&lt;name&gt;Anguilla&lt;/name&gt;
        ///		&lt;sameAreaRule&gt;G&lt;/sameAreaRule&gt;
        ///		&lt;longDistanceRule&gt;1FG&lt;/longDistanceRu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;mobiles xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;mobile&gt;
        ///		&lt;id&gt;+49151&lt;/id&gt;
        ///		&lt;countryID&gt;49&lt;/countryID&gt;
        ///		&lt;name&gt;T-Mobile (D1)&lt;/name&gt;
        ///	&lt;/mobile&gt;
        ///	&lt;mobile&gt;
        ///		&lt;id&gt;+491511&lt;/id&gt;
        ///		&lt;countryID&gt;49&lt;/countryID&gt;
        ///		&lt;name&gt;T-Mobile (D1)&lt;/name&gt;
        ///	&lt;/mobile&gt;
        ///	&lt;mobile&gt;
        ///		&lt;id&gt;+491512&lt;/id&gt;
        ///		&lt;countryID&gt;49&lt;/countryID&gt;
        ///		&lt;name&gt;T-Mobile (D1)&lt;/name&gt;
        ///	&lt;/mobile&gt;
        ///	&lt;mobile&gt;
        ///		&lt;id&gt;+491514&lt;/id&gt;
        ///		&lt;countryID&gt;49&lt;/countryID&gt;
        ///		&lt;name&gt;T-Mobile (D1)&lt;/na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mobiles {
            get {
                return ResourceManager.GetString("Mobiles", resourceCulture);
            }
        }
    }
}
